app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20210729194402_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
first set-up of the user model with devise
=> user model created with devise set-up

Gemfile, app/controllers/gardens_controller.rb, app/models/garden.rb, app/models/user.rb, app/views/gardens/_form.html.erb, app/views/gardens/index.html.erb, config/routes.rb, db/migrate/20210731104419_create_gardens.rb, db/schema.rb, test/controllers/gardens_controller_test.rb, test/models/garden_test.rb
=> created garden model and controller with routes

Gemfile, Gemfile.lock, app/views/gardens/index.html.erb, db/seeds.rb
check all changes just incase please lads
=> added a quick seed file and removed the form from index

app/controllers/bookings_controller.rb, app/models/booking.rb, app/models/garden.rb, app/views/bookings/create.html.erb, app/views/bookings/destroy.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, config/routes.rb, db/migrate/20210731112021_create_bookings.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/models/booking_test.rb
=> Bookmark model creation

app/views/pages/home.html.erb
=> button added

Gemfile, Gemfile.lock, app/assets/stylesheets/pages/_gardens_index.scss, app/controllers/gardens_controller.rb, app/javascript/packs/application.js, app/javascript/packs/init_mapbox.js, app/models/garden.rb, app/views/gardens/index.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, db/migrate/20210802104738_add_coordinates_to_gardens.rb, db/schema.rb, package.json, yarn.lock
I added a map with markers to the garden page
=> added map to gardens#index

app/controllers/gardens_controller.rb, app/views/bookings/index.html.erb, app/views/gardens/index.html.erb, app/views/gardens/show.html.erb
guys fixed major bug in controller and added show page
=> added show page and fixed major bug in garden controller

.ENV, app/assets/stylesheets/components/_card.scss, app/controllers/pages_controller.rb, app/models/user.rb, app/views/gardens/index.html.erb, app/views/pages/profile.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
included profile page with bookings and gardens(todo)
link to homepage on navbar
link to profile page from avatar
=> fixed some stuff

app/assets/stylesheets/application.scss, app/assets/stylesheets/gardens/_show.scss, app/views/gardens/show.html.erb
show page with a link to bookings
page
=> show page with button to booking

app/assets/stylesheets/components/_card.scss, app/controllers/bookings_controller.rb, app/views/gardens/index.html.erb, app/views/gardens/show.html.erb, app/views/pages/profile.html.erb
"booking added to garden and garden size taller
=> booking added to garden and garden size taller

app/assets/stylesheets/gardens/_show.scss, app/views/gardens/show.html.erb
=> fixed btn position in show

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_gardens_index.scss, app/controllers/gardens_controller.rb, app/javascript/packs/init_mapbox.js, app/models/garden.rb, app/views/gardens/_info_window.html.erb, app/views/gardens/index.html.erb, app/views/gardens/show.html.erb
i added a search bar that only searches by location but doesn't find by radius which would be the next step 
I also added a pop-up to the markers on the map to show title and address
the map has a small navigation window in the top right
lemme know what you guys think
=> added features to the map also added search bar

.gitignore, Gemfile, Gemfile.lock, app/controllers/bookings_controller.rb, app/controllers/gardens_controller.rb, app/models/garden.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/gardens/index.html.erb, app/views/gardens/new.html.erb, app/views/gardens/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20210804220201_create_active_storage_tables.active_storage.rb, db/schema.rb, db/seeds.rb
Active storage / cloudinary for users and gardens
Added a random seed with a selection of pics from gardens in cloudinary
BUNDLE INSTALL AFTER PULL
> will share key for cloudinary
=> cloudinary for users and gardens

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/pages/_home.scss, app/views/bookings/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
increased profile pic size
uploaded assets to cloudinary
changed link of bookings for gardens to profile pic
=> cloudinary for assets

app/views/pages/profile.html.erb
=> bookings now showing garden pics

app/assets/stylesheets/gardens/_show.scss, app/views/gardens/show.html.erb
forgive the name please guys i forgot to change branch to fix the issue
but auto complete is back to normal
=> fixed the autocomplete on new page

app/views/pages/home.html.erb
=> changed typo on home page

app/views/gardens/new.html.erb, app/views/gardens/show.html.erb, db/migrate/20210807103831_add_description_to_gardens.rb, db/schema.rb, db/seeds.rb
added migration to garden model
added input field to new garden
added the description into the show page
changed the seed file to make a description with lorem ipsum
=> added description

app/controllers/gardens_controller.rb, app/views/gardens/index.html.erb, app/views/gardens/show.html.erb
now user cannot book his own garden
if picture is not loaded a default one is shown and the view checks it with an if statement
.
=> fixed booking issues

app/controllers/gardens_controller.rb, app/models/garden.rb, app/views/gardens/new.html.erb, app/views/gardens/show.html.erb, app/views/shared/_navbar.html.erb
changed validations so the owner can upload multiple photos
then got carried away and added a carousel
=> Changevalidationphotos

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_profile.scss, app/views/pages/profile.html.erb
=> Profile page showing gardens

app/views/shared/_navbar.html.erb
Fixed a bug for avatar pictures to check whether it is present or not
=> avatar fixed

app/views/pages/profile.html.erb
order shown in bookings reversed to have the most updated ones on top
bookings.reverse
=> bookings.reverse

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_popup.scss, app/assets/stylesheets/components/_search-bar.scss, app/assets/stylesheets/gardens/_show.scss, app/controllers/gardens_controller.rb, app/controllers/reviews_controller.rb, app/models/garden.rb, app/models/review.rb, app/models/user.rb, app/views/gardens/_review.html.erb, app/views/gardens/index.html.erb, app/views/gardens/show.html.erb, app/views/reviews/new.html.erb, config/routes.rb, db/migrate/20210810130247_create_reviews.rb, db/schema.rb, test/controllers/reviews_controller_test.rb, test/models/review_test.rb
So in theory everything is working. we have nice pop-up windows and reviews architecture. problem is that the front end is still a mess. like a lot. I've slowed down buttons and changed the search bar to our style. still lots o work to do
=> i've started with the popup and ended up with full reviews

app/assets/stylesheets/application.scss, app/javascript/packs/application.js, app/views/bookings/_form_bookings.html.erb, app/views/bookings/new.html.erb, package.json, yarn.lock
flatpicker showing when booking
=> flatpickr basic included

app/views/layouts/application.html.erb, app/views/pages/secret.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
/secret page added with console and timer to redirect
=> Secret page

app/javascript/packs/init_mapbox.js
=> changed map style

app/assets/stylesheets/application.scss, app/controllers/pages_controller.rb, app/views/gardens/index.html.erb, app/views/pages/queen.erb, app/views/pages/secret.html.erb, config/routes.rb, db/seeds.rb
flatpicker green theme
added seed of reviews (MAYBE WE SHOULD REMOVE THE CREATION OF A REVIEW - YOU SHOULD BE ABLE TO ADD ONE ONY IF YOU HAVE RENTED THE GARDEN)
/secret now trigger typerhacker with a popup and redirect to /queen (with mask) after 20 seconds
=> improvements here and there

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/gardens/index.html.erb
i've added our style to sign up and create new user
=> i've added our style to sign up and create new user

app/views/pages/profile.html.erb
added condition for gardens without pictures
=> profile page bug fixed

app/assets/stylesheets/pages/_profile.scss
=> profile page has scrolling

app/views/gardens/index.html.erb
=> truncated garden title in index

app/views/gardens/index.html.erb
=> added review count to garden index

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_queen.scss, app/views/pages/queen.erb
=> nicer queen

app/views/gardens/index.html.erb
=> map size changed

app/views/gardens/index.html.erb
=> changed truncate
